# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Beatriz Bergamo
title: Bioinformatician and MSc student
email: beatrizrbergamo@gmail.com
# website: www.github.com/brbergamo/brbergamo.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  brbergamo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: beatriz-bergamo
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Beatriz! I’m a bioinformatician with a passion for multi-omics data analysis. I’m currently pursuing my Master’s in Bioinformatics at Boston University, where I’m rotating in a lab that explores RNA-Seq data from mouse models to understand gene expression patterns related to aging.
  
  I’m passionate about turning biological data into insights that drive new hypotheses and experiments - I get way too excited about that! I also focus on building efficient NGS pipelines and love creating visualizations that make complex datasets easy to interpret. With tools like R, Python, Git, Nextflow, Snakemake, BASH, and Linux, I streamline workflows for bioinformatics, and my experience with OCI and HPC lets me scale analyses to meet any challenge.
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
    - layout: top-middle
      border: weak
      title: RNA-Seq Alignment and Quantification Scripts
      link: github.com/brbergamo/bioinfo_scripts
      # link_text: Project Website
      additional_links:
        - title:  sproogen/modern-resume-theme
          icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A minimal set of HPC-compatible Bash scripts for RNA-Seq analysis.
        description: |
          This project includes two core scripts: one for aligning paired-end RNA-Seq reads using STAR, a splice-aware aligner, and another for gene-level quantification with featureCounts. Designed to run efficiently on a computing cluster, the scripts handle automatic detection of input files and parallel processing, producing sorted BAM files and a unified count matrix for downstream analysis.

Ideal for small- to medium-scale RNA-Seq experiments or as a lightweight starting point for building more complex NGS pipelines. 
      - layout: top-middle
        border: weak
        title: RShiny App for RNA-Seq Data Analysis
        link: github.com/brbergamo/rshiny-app-591r
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A Shiny app for interactive RNA-Seq data exploration and visualization.
        description: |
          This project is an interactive Shiny application designed to streamline RNA-Seq data analysis. The app allows users to explore sample metadata, filter and visualize gene expression counts, and perform differential expression analysis. 

          Key features include:
          - **Sample Metadata Exploration:** Summary tables, sortable data tables, and customizable visualizations such as histograms and density plots.
          - **Counts Matrix Analysis:** Gene filtering based on variance and expression thresholds, scatter plots for variance vs. median count, and clustered heatmaps with optional log transformation.
          - **Differential Expression Analysis (DEA):** Integration with DESeq2, limma, or edgeR, sortable tables of results, and visualizations like volcano plots.
          - **Principal Component Analysis (PCA):** Interactive selection of PCs for scatter plots, with variance explained displayed for each component.
          - **Gene Set Enrichment Analysis (GSEA):** Uses fgsea to perform pathway enrichment analysis with customizable filtering and visualization of top pathways.

          The app was built using **R Shiny**, leveraging packages such as **ggplot2, DESeq2, fgsea, DT, and gplots** to ensure an interactive and efficient data analysis workflow. It is ideal for researchers working with RNA-Seq data who want an accessible and customizable tool for exploratory data analysis and visualization.
      - layout: top-middle
        border: weak
        title: Rosalind
        link: github.com/brbergamo/Rosalind
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A collection of solutions to problems from the Rosalind platform.
        description: | # this will include new lines to allow paragraphs
          I created this project to solve bioinformatics challenges on the Rosalind platform using Python. It helped me sharpen my skills in algorithms and bioinformatics by working through real-world problems. I’ve shared these solutions to be helpful to others working through the same challenges, providing a resource they can learn from and build on. This project has been a great way to deepen my understanding of bioinformatics.
      - layout: top-middle
        title: KEGG Python Module and Notebook
        link: github.com/brbergamo/KEGG_API_scripts
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A set of Python tools for working with the KEGG API.
        description: |
          This is a project I created to streamline working with the KEGG (Kyoto Encyclopedia of Genes and Genomes) database. It includes a Jupyter notebook demonstrating how to use the KEGG API and a Python module that retrieves KEGG data and converts it into a CSV format for easier analysis. I developed this to improve my own workflow and to share with others who may find it useful in their bioinformatics projects. Hopefully, this tool can help others work more efficiently with KEGG while I continue to learn and improve through this project.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: ByMyCell - A Genomics and SynBio Startup
        link: bymycell.com.br
        # link_text: boringcompany.com
        sub_title: Bioinformatician - Ribeirao Preto, Brazil
        caption: August 2023 - August 2024
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Analyzed and processed metagenomics data to explore microbial diversity and metabolic potential, using NGS data from Nanopore and Illumina. I developed and automated bioinformatics pipelines with Nextflow, significantly improving workflow efficiency and reducing processing time.

            Enhanced the metabolic annotation pipeline by integrating tools like PICRUSt2 and MinPath, resulting in more accurate pathway predictions. Additionally, I applied advanced data analysis techniques to uncover patterns in the data, helping to better understand microbial functions and taxonomy.
      - layout: left
        border: weak
        title: Natural Products Metabolomics Laboratory
        # link_text: boringcompany.com
        sub_title: Undergraduate Researcher - Glasgow, Scotland
        caption: October 2022 - April 2023
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: |
          Selected for a competitive exchange program with only one position offered and awarded a scholarship to work at the University of Strathclyde. Worked on a co-culture project to analyze the metabolites produced by MRSA and fungi under competitive growth conditions. The goal of the research was to identify bioactive compounds with anti-biofilm properties, using techniques such as thin-layer chromatography (TLC), microbiological culture, and metabolite extraction to isolate and analyze potential compounds.

          In addition to conducting lab work, I applied multivariate data analysis (PCA, PLS-DA) using SIMCA to identify key differences in metabolite profiles between different conditions. These analyses helped uncover potential bioactive compounds and provided valuable insights into the metabolic interactions between microbial species. This project strengthened my understanding of metabolomics and equipped me with practical skills in experimental design and data interpretation.
      - layout: left
        border: weak
        title: Van der Hooft Computational Metabolomics Group
        # link_text: boringcompany.com
        sub_title: Undergraduate Researcher - Remote
        caption: January 2022 - December 2023
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: |
          Collaborated on a project comparing spectral similarity and variable selection tools in large-scale mass spectrometry experiments. My work focused on testing and optimizing pyMUVR, a machine learning-based variable selection tool, with large metabolomics datasets. This involved evaluating its effectiveness for improving feature selection and overall analysis accuracy.

          Additionally, I developed a Python-based web application to host pyMUVR, creating an accessible and user-friendly interface for researchers.
      - layout: left
        title: Natura & Co
        link: naturaeco.com/who-we-are/
        sub_title: Undergraduate Researcher - Remote
        caption: July 2020 - July 2021
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: |
          Developed a methodology to link metagenomic data with bacterial functional data as part of a research project that became a finalist in the Embrace Award 2021. Focused on analyzing 16S sequencing data using bioinformatics tools like QIIME2, PICRUSt2, and Cytoscape to investigate microbial communities and their functional potential.

          Programmed in Python to perform univariate statistical analyses, extracting key insights from the data. Automated data processing workflows using Snakemake, which improved the efficiency and reproducibility of the entire analysis pipeline.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Boston University
        caption: 2024 - Present
        sub_title: MSc in Bioinformatics
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic #pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I’m currently pursuing my Master’s in Bioinformatics at Boston University, where I’m developing key skills in data analysis and teamwork. My coursework focuses on bioinformatics and multi-omics data analysis, and I use these skills regularly in my research work.

          I also participate in events by GWISE (Graduate Women in Science and Engineering), including career mentoring events and the Cambridge Science Festival, where I engage with the community and promote STEM education for children.
      - layout: left
        title: University of Sao Paulo
        caption: 2024
        sub_title: BSc in Pharmaceutical Sciences and Biochemistry
        description: |
          I completed my Bachelor's degree in Pharmaceutical Sciences at the University of São Paulo (USP), the top university in Latin America and the Caribbean according to the QS World University Ranking. During my studies, I developed strong skills in research, data analysis, and teamwork, particularly through bioinformatics projects in metagenomics and metabolomics at the [Computational Chemical Biology Laboratory (CCBL)](http://ccbl.fcfrp.usp.br/ccbl/), where I gained foundational expertise in computational methods to analyze complex biological datasets.

          In addition to my academic work, I was actively involved in the student community as the Director of the Cultural Department at the "Lourenço Roselino" Academic Center. My role included organizing cultural events, coordinating fundraising, and promoting integration among pharmacy students. These experiences helped me build leadership and event organization skills while contributing to the broader student community.

  - title: When I’m Not Working
    layout: text
    content: | # this will include new lines to allow paragraphs
      Outside of bioinformatics, I like spending time outdoors at parks, enjoying nature, and going on long walks.

      I also love visiting different coffee shops and finding new places to relax with a good book. Reading and watching movies are my favorite ways to unwind, whether it's diving into a good story or just something fun and light.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
