# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Beatriz Bergamo
title: Bioinformatician and MSc student
email: beatrizrbergamo@gmail.com
# website: www.github.com/brbergamo/brbergamo.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  brbergamo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: beatriz-bergamo
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Beatriz! I’m a bioinformatician with a passion for multi-omics data analysis. I’m currently pursuing my Master’s in Bioinformatics at Boston University and working as a Graduate Researcher at the Fiszbein Lab, where I explore RNA-Seq data from mouse models to understand gene expression patterns related to aging.
  
  I’m passionate about developing efficient pipelines for NGS data processing, and I also love creating clear visualizations that make complex datasets easier to interpret. With experience in tools like R, Python, Git, Nextflow, Snakemake, BASH, and Linux, I’m skilled at optimizing workflows for bioinformatics analysis. Additionally, I have experience with cloud computing platforms like OCI and high-performance computing (HPC), which allow me to scale and streamline data analysis.
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Rosalind
        link: github.com/brbergamo/Rosalind
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A collection of solutions to problems from the Rosalind platform.
        description: | # this will include new lines to allow paragraphs
          I created this project to solve bioinformatics challenges on the Rosalind platform using Python. It helped me sharpen my skills in algorithms and bioinformatics by working through real-world problems. I’ve shared these solutions to be helpful to others working through the same challenges, providing a resource they can learn from and build on. This project has been a great way to deepen my understanding of bioinformatics while contributing to the learning of others.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ByMyCell - A Genomics and SynBio Startup
        link: bymycell.com.br
        # link_text: boringcompany.com
        sub_title: Bioinformatician
        caption: August 2023 - August 2024
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Led the analysis and processing of metagenomics data to study microbial diversity and metabolic potential, utilizing NGS data from Nanopore and Illumina. I developed and automated bioinformatics pipelines using Nextflow, significantly increasing workflow efficiency and reducing processing time.  
            
            Improved the metabolic annotation pipeline by integrating tools like PICRUSt2 and MinPath, leading to more accurate pathway predictions. Additionally, I applied advanced data analysis techniques to uncover patterns in the data, which helped to better understand microbial functions and taxonomy. This work provided valuable insights to the company's clients, enhancing their research outcomes.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Boston University
        caption: 2024 - Present
        sub_title: MSc in Bioinformatics
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic #pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I’m currently pursuing my Master’s in Bioinformatics at Boston University, where I’m developing key skills in data analysis and teamwork. My coursework focuses on bioinformatics and multi-omics data analysis, and I use these skills regularly in my research work.

          I also participate in events by GWISE (Graduate Women in Science and Engineering), including career mentoring events and the Cambridge Science Festival, where I engage with the community and promote STEM education for children.
      - layout: left
        title: University of Sao Paulo (USP)
        caption: 2024
        sub_title: BSc in Pharmaceutical Sciences and Biochemistry
        description: |
          I completed my Bachelor's degree in Pharmaceutical Sciences at the University of São Paulo (USP), the top university in Latin America and the Caribbean according to the QS World University Ranking. During my studies, I developed strong skills in research, data analysis, and teamwork, particularly through my work at the Computational Chemical Biology Laboratory (CCBL), where I first learned bioinformatics and collaborated with colleagues on computational projects involving biological data.

          In addition to my academic work, I was actively involved in the student community as the Director of the Cultural Department at the "Lourenço Roselino" Academic Center. My role included organizing cultural events, coordinating fundraising, and promoting integration among pharmacy students. These experiences helped me build leadership and event organization skills while contributing to the broader student community.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I’m not busy with bioinformatics, you’ll often find me enjoying the outdoors at local parks, appreciating nature and taking long walks. 
      
      I love exploring different coffee shops and discovering new cozy spots to relax with a good book. Reading is one of my favorite ways to unwind, along with watching a variety of movies—whether it’s a thought-provoking film or just something lighthearted. These activities help me recharge and find inspiration in everyday moments.


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
